kind: Service
apiVersion: v1
metadata:
  name: indexer
  labels:
    app: indexer
spec:
  ports:
    - name: finder
      port: 3000
      targetPort: finder
    - name: ingest
      port: 3001
      targetPort: ingest
  selector:
    app: indexer
  type: ClusterIP
  clusterIP: None
