apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: indexer
spec:
  serviceName: "indexer"
  replicas: 1
  selector:
    matchLabels:
      app: indexer
  template:
    metadata:
      labels:
        app: indexer
    spec:
      securityContext:
        runAsUser: 10001
        fsGroup: 532
      containers:
        - name: indexer
          image: storetheindex
          envFrom:
            - configMapRef:
                name: indexer-env-vars
          ports:
            - containerPort: 3000
              name: finder
            - containerPort: 3001
              name: ingest
            - containerPort: 3002
              name: admin
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /config
          readinessProbe:
            httpGet:
              port: finder
              path: /health
            initialDelaySeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 5
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: indexer-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Ti
