apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: storetheindex

resources:
  - indexer-statefulset.yaml
  - indexer-service.yaml
  - pdb.yaml
  - indexer-config.yaml

transformers:
  - labels.yaml

configMapGenerator:
  - name: indexer-env-vars
    behavior: create
    literals:
      - GOLOG_LOG_LEVEL=INFO
      - GOLOG_LOG_FMT=json
      - STORETHEINDEX_LOTUS_GATEWAY=wss://api.chain.love
      - STORETHEINDEX_PATH=/config
      - STORETHEINDEX_LISTEN_ADMIN=/ip4/0.0.0.0/tcp/3002
      - STORETHEINDEX_WATCH_CONFIG=true
