version: "3.3"

services:
  index-provider:
    container_name: index-provider
    image: node:22
    volumes:
      - .:/home/plebbit-ipni
    working_dir: /home/plebbit-ipni
    entrypoint: bin/index-provider daemon
    environment:
      PROVIDER_PATH: .index-provider
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "5"

  storetheindex:
    container_name: storetheindex
    image: node:22
    volumes:
      - .:/home/plebbit-ipni
    working_dir: /home/plebbit-ipni
    entrypoint: bin/storetheindex daemon
    environment:
      STORETHEINDEX_PATH: .storetheindex
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "5"

  indexstar:
    container_name: indexstar
    image: node:22
    volumes:
      - .:/home/plebbit-ipni
    working_dir: /home/plebbit-ipni
    entrypoint: bin/indexstar --listen :7777 --backends http://127.0.0.1:3000 --providersBackends http://no
    environment:
      INDEXSTAR_PATH: .indexstar
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    working_dir: /home/plebbit-ipni
    volumes:
      - .:/home/plebbit-ipni

  proxy-server:
    container_name: proxy-server
    image: node:22
    volumes:
      - .:/home/plebbit-ipni
    working_dir: /home/plebbit-ipni
    entrypoint: sh -c "npm install && node ./proxy-server"
    restart: always
    ports:
      - "80:80"
    logging:
      options:
        max-size: "10m"
        max-file: "5"
