apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: external-dns
spec:
  selector:
    matchLabels:
      app: external-dns
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      containers:
        - name: external-dns
          args:
            - --source=service
            - --source=ingress
            - --domain-filter=prod.cid.contact
            - --provider=aws
            - --policy=upsert-only
            - --aws-zone-type=public
            - --registry=txt
            - --txt-owner-id=Z0812180J6HXR2V3GIFI # prod.cid.contact hosted zone ID; see terraform output `prod_cid_contact_zone_id`
