apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns

resources:
  - ../../../../base/external-dns
  - namespace.yaml

patchesStrategicMerge:
  - deploy-patch.yaml
  - sa-patch.yaml
