version: 2
builds:
  - main: ./provider
    dir: cmd
    binary: provider
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 'amd64'
release:
  # Do not override manually written release notes.
  mode: keep-existing
changelog:
  # Do not generate changelog since for this project release notes are written manually.
  disable: true
