apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system

resources:
  - https://github.com/fluxcd/flux2/releases/download/v0.28.5/install.yaml

patches:
  # Disallow cross namespace access, since the deployment follows a multi-tenant setup.
  - patch: |
      - op: add
        path: /spec/template/spec/containers/0/args/0
        value: --no-cross-namespace-refs=true
    target:
      kind: Deployment
      name: "(kustomize-controller|helm-controller|notification-controller|image-reflector-controller|image-automation-controller)"
  # Authenticate EKS with ECR automatically, used to pull images for deployment.
  - patch: |
      - op: add
        path: /spec/template/spec/containers/0/args/0
        value: --aws-autologin-for-ecr
    target:
      kind: Deployment
      name: image-reflector-controller
  # Require separate service account set up per tenant, since the deployment follows a multi-tenant setup.
  - patch: |
      - op: add
        path: /spec/template/spec/containers/0/args/0
        value: --default-service-account=default
    target:
      kind: Deployment
      name: "(kustomize-controller|helm-controller)"
  # Allow cluster-wide kustomizations to administer the cluster.
  - patch: |
      - op: add
        path: /spec/serviceAccountName
        value: kustomize-controller
    target:
      kind: Kustomization
      name: flux-system
