apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: promtail

resources:
  - daemonset.yaml
  - rbac.yaml

configMapGenerator:
  - name: promtail-config
    files:
      - config.yaml
  - name: promtail-env
    literals:
      - PROMTAIL_URL=http://localhost:1234/loki/api/v1/push
      - PROMTAIL_TENANT_ID=
      - PROMTAIL_LABEL_OWNER=
      - PROMTAIL_LABEL_ENV=
      - PROMTAIL_LABEL_REGION=

secretGenerator:
  - name: promtail-auth
    envs:
      - auth.env
