apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: bedrock@protocol.ai
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - dns01:
          route53:
            region: us-east-2
        selector:
          dnsZones:
            - prod.cid.contact
