apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::407967248065:role/prod/us-east-2/cert_manager"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-webhook
  namespace: cert-manager
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::407967248065:role/prod/us-east-2/cert_manager"
